apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: plugin-
  labels:
    workflows.argoproj.io/test: "true"
  annotations:
    hello: "initial"
    workflows.argoproj.io/description: |
      This example shows how to use the build-in hello plugin. The plugin will change the "hello" annotation from
      "greetings" to "goodbye" and it will mark the hello step as successful.
    workflows.argoproj.io/verify.py: |
      assert status["phase"] == "Succeeded"
spec:
  entrypoint: main
  templates:
    - name: main
      plugin:
        hello: { }